services:
  - type: web
    name: trellis-frontend
    runtime: static
    repo: https://github.com/oxanashva/trellis-app.git
    rootDir: ./trellis-frontend
    staticPublishPath: ./build
    autoDeployTrigger: "off"
