services:
  trellis-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # These now look for variables on your machine/shell
        VITE_CLOUD_NAME: ${VITE_CLOUD_NAME}
        VITE_API_URL: ${VITE_API_URL}
        VITE_LOCAL: false
    container_name: trellis-running
    ports:
      - "3030:3030"
    env_file:
      - ./trellis-backend/.env
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: trellis-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: trellis-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

volumes:
  elastic-data: